### ISSUE TITLE
Implement keysend / static payment requests

### ISSUE THREAD

**Issue by t-bast** [ACINQ/lightning-kmp#144]

**Comment by lndhub-admin** [comment]
a keysend could have a data payload asking for a dictionary of services provided by node - and in-turn then send command by another keysend activating a service . this would be a dynamic decentralized dictionary not a stale consensus ridden feature flag space limited one ...

great wouldn't You say ...

**Comment by t-bast** [comment]
We will add support for Bolt 12 payments. No need to track it in this issue.
