### ISSUE TITLE
Error decoding invoice with large amount

### ISSUE THREAD

**Issue by theborakompanioni** [ACINQ/lightning-kmp#470]
When decoding the following [invoice](https://lightningdecoder.com/lnbcrt11pj8wdh7sp5p2052f28az75s3eauqjskcwrzrjujf7rfqspsvk6hgppywytrdzspp5670t00mwakdy0l5w3lnw4rhdgnv4ctep974am6jp0zma627fhdfsdqqxqyjw5qcqp29qyysgqh2ce2cmptj33l35a9pt2l603aa34jpj8p35s302l0lhuujmtmkghrmkadv456h3rpsxjpschnpt5ugzltqsjtauvnfy799aufapav6gp202th5), an exception is raised at `require(pr.signedPreimage().contentEquals(tohash))`.
The invoice is of (rather large) amount `100_000_000_000 msats`. 

```
lnbcrt11pj8wdh7sp5p2052f28az75s3eauqjskcwrzrjujf7rfqspsvk6hgppywytrdzspp5670t00mwakdy0l5w3lnw4rhdgnv4ctep974am6jp0zma627fhdfsdqqxqyjw5qcqp29qyysgqh2ce2cmptj33l35a9pt2l603aa34jpj8p35s302l0lhuujmtmkghrmkadv456h3rpsxjpschnpt5ugzltqsjtauvnfy799aufapav6gp202th5
```

```
java.lang.IllegalArgumentException: Failed requirement.
	at fr.acinq.lightning.payment.PaymentRequest$Companion.read(PaymentRequest.kt:233)
	at com.example.LightningKmpInvoiceTest.itShouldDecodeInvoiceSuccessfully(InvoiceConverterTest.java:111)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

`Hex.encode(pr.signedPreimage())`:
```
6c6e62637274313030303030306d0c8ee6c4700d30c533a434f7e6d7c788df5f787058836ffa754af7dfa38561fb6125f3b807088021a332d9e67dfddecd20460886d324b8c859557aacc3d7d352272e240789850320583400300927501800545010904000
```

`Hex.encode(tohash)`:
```
6c6e62637274313030300c8ee6c4700d30c533a434f7e6d7c788df5f787058836ffa754af7dfa38561fb6125f3b807088021a332d9e67dfddecd20460886d324b8c859557aacc3d7d352272e240789850320583400300927501800545010904000
```

Same behaviour with an [invoice](https://lightningdecoder.com/lnbcrt10001pj8wd3rsp5cv2vayxnm7d4783r0477rstzpkl7n4ftmalgu9v8akzf0nhqrs3qpp5vednenalh0v6gzxpzrdxf9cepv4274vc0tax5389cjq0zv9qvs9sdqqxqyjw5qcqp29qyysgqk5f8um72jlnw9unjltdgxw9e2fvec0cxq05tcwuen2jpu42q4p9pt2djk2ysu62nkpg49km59wrexm0wt3msevz53fr2tfnqxf5sdnqpu8th97) of amount `100_000_000_000_000 msats`:
```
lnbcrt10001pj8wd3rsp5cv2vayxnm7d4783r0477rstzpkl7n4ftmalgu9v8akzf0nhqrs3qpp5vednenalh0v6gzxpzrdxf9cepv4274vc0tax5389cjq0zv9qvs9sdqqxqyjw5qcqp29qyysgqk5f8um72jlnw9unjltdgxw9e2fvec0cxq05tcwuen2jpu42q4p9pt2djk2ysu62nkpg49km59wrexm0wt3msevz53fr2tfnqxf5sdnqpu8th97
```

---

The exception is **NOT raised** with an [invoice](https://lightningdecoder.com/lnbcrt100m1pj8wwq5sp5cylu7386jfk4waf2h2dwpjlps5rqgz33vt3mc9mf0gkrm6gnpylspp5eeves0k77hk9l0pfjxzhhuyusutdme9detavkdycp2e2huw3at5qdqqxqyjw5qcqp29qyysgqstvreh8s4w7r8e3qkdchvjzql8vdzv4gkt03k5s4wc5krkhgwszkdrstlm9y7mwcktp70sqrft8z5xkxzvn5v4crl6zh72p3jf8xjfcqxkuqgz), of amount `10_000_000_000 msats` (10x less than the first one above):
```
lnbcrt100m1pj8wwq5sp5cylu7386jfk4waf2h2dwpjlps5rqgz33vt3mc9mf0gkrm6gnpylspp5eeves0k77hk9l0pfjxzhhuyusutdme9detavkdycp2e2huw3at5qdqqxqyjw5qcqp29qyysgqstvreh8s4w7r8e3qkdchvjzql8vdzv4gkt03k5s4wc5krkhgwszkdrstlm9y7mwcktp70sqrft8z5xkxzvn5v4crl6zh72p3jf8xjfcqxkuqgz
```

---

All invoices have been created with CLN `v22.11.1` on `regtest`.

Any hint or feedback is highly appreciated :pray:

**Comment by theborakompanioni** [comment]
> The issue with your invoices is that they contain a description field, but it is empty. There have been discussions about that recently on the specification, but it's currently generally accepted that invoices without description or description hash are invalid.

Thanks for the clarification. How come the other invoice is parsed correctly?

**Comment by t-bast** [comment]
That's strange, you're right! I'll look into it in more details, there must be something else...

**Comment by t-bast** [comment]
Thanks for the report, you're totally right, this is a bug on our side! We simply don't handle amount that are multiples of 1BTC, because we interpreted the specification as requiring one of the defined currency multipliers: we thus encode 1BTC as `1000m` (1000 mBTC) which creates a mismatch.
