### ISSUE TITLE
Decoding bolt12

### ISSUE THREAD

**Issue by michaelWuensch** [ACINQ/lightning-kmp#691]
Hi, I tried to use the library to decode the following bolt 12 offer created with CoreLightning on regtest:

lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrc2q36x2um5zcss9g069rpwu3yvah7ryysy5yxx9amsfq7707cgd8pesxudttdawsnj

The decoding fails because the hrp does not match. Core lightning creates it with "lno" and here it is checked against "lni"
https://github.com/ACINQ/lightning-kmp/blob/master/src/commonMain/kotlin/fr/acinq/lightning/payment/Bolt12Invoice.kt#L84

Is this a bug or am I doing the decoding wrong? (I used the "fromString" method of the companion)

**Comment by pm47** [comment]
You need to use `OfferTypes.Offer.decode(offer)`. Invoices (`lni`) and offers (`lno`) are different things.

Please use [discussions](https://github.com/ACINQ/lightning-kmp/discussions) for questions.

**Comment by michaelWuensch** [comment]
Thanks, that works! :)
